name: Test Copy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy to Remote Server
      uses: ./ 
      with:
        host: ${{ vars.HOST }}
        ssh_port: ${{ vars.PORT }}
        ssh_username: ${{ vars.USERNAME }}
        ssh_key: ${{ vars.SSHKEY }}
        ssh_passphrase: ${{ vars.PSW }}
        source_dir: "test"
        destination_dir: home/projeto3
        rm: true
